Build proper connection string on refresh_slots
Marwes/redis-cluster-rs pull request #15
Opened 2023-02-10 07:00 UTC by trungda

If `username` and `password` are provided in the initial connection strings, we should use them to build connection strings on `get_slot`. Currently, when using username and password to log in to the cluster, we would fail to create connection string on refresh because we drop the `username` and `password` when building the connection strings.

2023-02-10 07:04 UTC, trungda commented
@Marwes Could you help take a look at this PR? We use redis with ACL enabled in production and `get_slots` is broken currently.

2023-02-11 20:15 UTC, Marwes approved these changes

2023-02-12 01:03 UTC, trungda commented
Thanks @Marwes! I have another commit just to make ci pass. Could you help take a look again? Thank you!

2023-02-21 14:09 UTC, Marwes commented
Still seeing CI failures :(

2023-02-23 17:31 UTC, trungda commented
> Still seeing CI failures :(

Oh I think it's the old run, somehow, I can't trigger a new run with the new commit.

2023-02-23 18:31 UTC, trungda commented
> Still seeing CI failures :(

Strange. Let me take a look. It's hard to repro locally.

2023-02-25 05:36 UTC, trungda commented
> 



> Still seeing CI failures :(

@Marwes I think this will work now. We need to sleep a bit longer to make sure the username/password are created in all nodes in the cluster for the test to pass.

2023-03-01 18:42 UTC, trungda commented
@Marwes could you help take a look? Thank you!

2023-03-05 05:16 UTC, trungda commented
Strange. I am not able to repro this locally :( 

```
test tests::slot ... ok
test tests::test_get_username_password ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running `/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/basic-66e85220c66a4142 --test-threads=1`

running 8 tests
test basic_cmd ... ok
test basic_eval ... ok
test basic_failover ... ok
test basic_pipe ... ignored
test basic_script ... ignored
test error_in_inner_connection ... ok
test proptests ... ok
test test_refresh_slot ... ok

test result: ok. 6 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 89.40s

     Running `/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/mock-5bd05d1558e51cfa --test-threads=1`

running 3 tests
test rebuild_with_extra_nodes ... ok
test tryagain_exhaust_retries ... ok
test tryagain_simple ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.15s

   Doc-tests redis_cluster_async
     Running `rustdoc --edition=2018 --crate-type lib --crate-name redis_cluster_async --test /Users/trungdinh/projects/redis-cluster-async/src/lib.rs -L dependency=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps -L dependency=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps --test-args --test-threads=1 --extern anyhow=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libanyhow-48d0b8c843a0548e.rlib --extern crc16=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libcrc16-ac0acb98b10997f4.rlib --extern env_logger=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libenv_logger-7846d043c5eb7318.rlib --extern futures=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libfutures-3cbb9b3a8628f735.rlib --extern log=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/liblog-b2a22b4c09e21c76.rlib --extern once_cell=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libonce_cell-156fe7cadf182844.rlib --extern pin_project_lite=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libpin_project_lite-41ab568fd3479b8a.rlib --extern proptest=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libproptest-96590af48e2d67ab.rlib --extern rand=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/librand-a15e8e217a1088dd.rlib --extern redis=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libredis-d7a3d64376f99118.rlib --extern redis_cluster_async=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libredis_cluster_async-2728a39ee53b4e09.rlib --extern tokio=/Users/trungdinh/projects/redis-cluster-async/target/debug/deps/libtokio-03912554faf5b903.rlib -C embed-bitcode=no --error-format human`

running 2 tests
test src/lib.rs - (line 11) ... ok
test src/lib.rs - (line 29) ... ok
```

2023-03-08 17:24 UTC, trungda commented
@Marwes I've removed the integration test. I will debug later when I have permission to run workflow myself just so I don't have to bother you. Could you help take a look again? Thank you!

2023-03-13 00:49 UTC, 2ico requested changes
Running Pipeline::refresh_slots() with a single cluster node with username and password returns an empty list of connection, thus setting Pipeline.connections to size=0

2023-03-13 01:26 UTC, 2ico commented
I investigated a bit more, the error is caused by addr being in the format `redis://user:password@:port` (without hostname) at line https://github.com/trungda/redis-cluster-async/blob/45d025158952d6e3a7702387708c2164a4b5b983/src/lib.rs#L559.

2023-03-13 03:12 UTC, trungda commented
> I investigated a bit more, the error is caused by addr being in the format `redis://user:password@:port` (without hostname) at line https://github.com/trungda/redis-cluster-async/blob/45d025158952d6e3a7702387708c2164a4b5b983/src/lib.rs#L559.

Thanks but in the test, I did specify a full connection string `redis://user:password@host:port`, i.e., `AUTHENTICATED_REDIS_URL: &str = "redis://client-user:redis-password@127.0.0.1:7000/";`.
That said, this is still an improvement. I'll merge.

2023-03-13 12:02 UTC, 2ico commented
> > I investigated a bit more, the error is caused by addr being in the format `redis://user:password@:port` (without hostname) at line https://github.com/trungda/redis-cluster-async/blob/45d025158952d6e3a7702387708c2164a4b5b983/src/lib.rs#L559.
> 
> Thanks but in the test, I did specify a full connection string `redis://user:password@host:port`, i.e., `AUTHENTICATED_REDIS_URL: &str = "redis://client-user:redis-password@127.0.0.1:7000/";`. That said, this is still an improvement. I'll merge.

I'm also specifying the full connection string. The "broken" one comes from the `CLUSTER SLOTS` command.
```~ ❯ redis-cli -u redis://default:PASSWORD@HOST:7000
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
192.168.122.188:7000> CLUSTER SLOTS
1) 1) (integer) 0
   2) (integer) 16383
   3) 1) ""
      2) (integer) 7000
      3) "162b9413fd3ff11e2b1648d7c3ade77288cedd9c"
```

2023-03-23 03:35 UTC, trungda commented
@Marwes could you help take a look and merge this? Thank you!

2023-04-01 17:33 UTC, trungda commented
@Marwes could you help take a look? Thank you!

2023-04-05 11:10 UTC, closed without merging

2023-04-05 11:23 UTC, Marwes commented
redis-cli wasn't installed on CI so those ACL commands couldn't run, I moved them into the test setup (in Rust) instead. Released in 0.8

2023-04-05 21:38 UTC, trungda commented
> redis-cli wasn't installed on CI so those ACL commands couldn't run, I moved them into the test setup (in Rust) instead. Released in 0.8

I see. Good to know that redis-cli is not installed :)